
---
dist: xenial
language: python
python: 3.7
services: docker
install:
- git clone --branch=v2.7.0 --depth=1 https://github.com/getpopper/popper /tmp/popper
- pip install /tmp/popper/src
- export PYTHONUNBUFFERED=1
script:
- cd popper_solution
- popper run -f wf.yml
